- name: download-artifact
  hosts: docker-host
  become: 'yes'
  become_user: docker-admin
  tasks: 
   - name: copy the jfrog.ssh
     copy: src=/opt/app-files/jfrog.sh dest=./app-files
   - name: copy the docker file to docker host
     copy: src=/opt/app-files/Dockerfile dest=./app-files
